name: Wiki Watcher

on:
  gollum:

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Gollum Page Watcher
        uses: benmatselby/gollum-page-watcher-action@v1
        env:
          SLACK_WEBHOOK: ${{ secrets.DISCORD_WIKI_WEBHOOK }}
          SLACK_USERNAME: TF2Autobot Wiki  # Overrides the webhook name in Discord
          # PAGES_TO_WATCH: (^Home$)|(^Setup) # Optional: Uncomment and use regex if you only want alerts for specific pages
